---
title: "Jay's Shiny App"
output: 
  flexdashboard::flex_dashboard:
    theme:
      version: 4
      bg: "#FFFFFF"
      fg: "#0A2240"
      base_font:
        google: "Poppins"
    orientation: rows
    vertical_layout: fill


runtime: shiny
---

```{r global, include=FALSE}
library(flexdashboard)
library(shiny)
library(tidyverse)
library(plotly)
library(plyr)
library(thematic)
```

Inputs {.sidebar}
-----------------------------------------------------------------------

```{r}

fileInput("file", "Data", buttonLabel = "Upload...")
textInput("delim", "Delimiter (leave blank to guess)", "")
numericInput("rows", "Rows to preview", 10, min = 1)

tags$hr()

selectInput('input1', "Variable Selector for Aggregate Counts", choices = NULL)

observeEvent(input$file,{
  if(is.null(raw())){return ()}
  updateSelectInput(session,'input1', 
            choices = colnames(raw()))
})

tags$hr()

selectInput('chart', "View Chart", choices = c("Not Displayed", "Histogram"), selected = NULL)

```

```{r}

raw <- reactive({
    req(input$file)
    delim <- if (input$delim == "") NULL else input$delim
    vroom::vroom(input$file$datapath, delim = delim)
  })
  

```


## Row 1 {.tabset}
### Raw Data

```{r}

renderTable(head(raw(), input$rows))


```

### Structure

```{r}

renderPrint({
    if(is.null(input$file)){return ()}
    str(input$file)
  })

```


### Summary

```{r}

renderTable({
    if(is.null(raw())){return ()}
  skimr::skim(raw())
})
  
```

### Aggregate Counts

```{r}

agg <- reactive({
  if(is.null(raw())){return ()}
  raw() %>% 
    group_by_(input$input1) %>%
    dplyr::summarise(Count = n()) %>%
    mutate(Proportion =round((Count/sum(Count)*100), digits = 1)) %>%
    arrange(desc(Proportion))
})

renderTable({
  if(is.null(raw())){return ()}
  agg()
})
  
```

### Chart

```{r}
renderPlotly({
if(is.null(raw())){return ()}
if(input$chart == "Not Displayed"){return()}
if(input$chart == "Histogram"){return(
ggplot(agg(), aes(x = input$input1, y = Proportion)) +
    geom_col(stat = "identity", group = input$input1) +
    labs(title = c("Histogram: ",input$input1), xlab = input$input1)+
    theme(legend.position = "none")+
    scale_y_continuous()
)}

})



```